language: java
jdk:
  - oraclejdk8

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file_glob: true
  file: '*-java-sdk/build/libs/*.jar'
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew bintrayUpload
